### ISSUE TITLE
How to use it angular2 typescript project?

### ISSUE THREAD

**Issue by NikasZalias** [KeithHenry/chromeExtensionAsync#1]
Hey, I downloaded source from npm. What class shout I add in my ngModules imports? I could find any exporting class..

**Comment by KeithHenry** [comment]
You should be able to reference `chrome-extension-async.d.ts` to get TypeScript definitions. The Chrome API is fairly large, so that definition file is just a massive list of namespaces with export functions - it's essentially a fork from the typings for the regular Chrome API with the addition of the `Promise` return types.

**Comment by KeithHenry** [comment]
An `@NgModule` is an Angular module, which this isn't. This is a wrapper for the Chrome API - you can use it in browser extensions or Chrome OS apps and inside them you can use Angular.

I'm not really an expert in Angular but it should be possible to write an `@NgModule`  variant of the TS definitions - if you want to contribute that a PR would be welcome (though it isn't in my personal roadmap).
